-- ================================================================
-- BE-566: WhatsApp Mac 本地归档结构化事实层
-- 仅新增 wa_* 表；不修改 CRM、文件中心和既有迁移。
-- 所有自然唯一键不包含 deleted，重新同步时恢复/更新原行。
-- ================================================================

CREATE TABLE `wa_account` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'WhatsApp账号ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `source_type` varchar(20) NOT NULL COMMENT '数据源类型: MAC_APP/BUSINESS_PLATFORM',
  `account_jid` varchar(191) NOT NULL COMMENT '源账号JID',
  `phone_normalized` varchar(32) DEFAULT NULL COMMENT '标准化号码(E.164 digits-only)',
  `display_name` varchar(100) DEFAULT NULL COMMENT '账号显示名',
  `app_version` varchar(32) DEFAULT NULL COMMENT '源App版本',
  `source_instance_hash` binary(32) DEFAULT NULL COMMENT '源实例匿名SHA-256指纹',
  `last_success_batch_id` bigint DEFAULT NULL COMMENT '最近成功导入批次ID',
  `last_sync_time` datetime(3) DEFAULT NULL COMMENT '最近成功同步时间(UTC)',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态: 1启用 0停用',
  `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '删除标记: 0正常 1删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wa_account_source` (`tenant_id`, `source_type`, `account_jid`),
  KEY `idx_wa_account_status` (`tenant_id`, `status`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='WhatsApp数据源账号';

CREATE TABLE `wa_import_batch` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '导入批次ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `account_id` bigint NOT NULL COMMENT 'WhatsApp账号ID',
  `batch_no` varchar(64) NOT NULL COMMENT 'Collector生成的幂等批次号',
  `snapshot_at` datetime(3) NOT NULL COMMENT '消息主库快照时点(UTC)',
  `source_app_version` varchar(32) DEFAULT NULL COMMENT '源App版本',
  `chat_schema_hash` binary(32) DEFAULT NULL COMMENT 'ChatStorage schema SHA-256',
  `contact_schema_hash` binary(32) DEFAULT NULL COMMENT 'Contacts schema SHA-256',
  `status` varchar(20) NOT NULL COMMENT '状态: RUNNING/SUCCEEDED/PARTIAL/FAILED',
  `source_row_count` bigint NOT NULL DEFAULT 0 COMMENT '扫描源行数',
  `logical_message_count` bigint NOT NULL DEFAULT 0 COMMENT '逻辑消息数',
  `inserted_count` bigint NOT NULL DEFAULT 0 COMMENT '新增数',
  `updated_count` bigint NOT NULL DEFAULT 0 COMMENT '更新数',
  `duplicate_count` bigint NOT NULL DEFAULT 0 COMMENT '重复源行数',
  `error_count` bigint NOT NULL DEFAULT 0 COMMENT '错误数',
  `manifest_json` json DEFAULT NULL COMMENT '脱敏快照manifest',
  `error_summary` varchar(1000) DEFAULT NULL COMMENT '脱敏错误摘要',
  `started_at` datetime(3) NOT NULL COMMENT '开始时间(UTC)',
  `completed_at` datetime(3) DEFAULT NULL COMMENT '完成时间(UTC)',
  `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '保留字段，审计批次不提供删除动作',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wa_batch_no` (`tenant_id`, `batch_no`),
  KEY `idx_wa_batch_account_time` (`tenant_id`, `account_id`, `started_at`),
  KEY `idx_wa_batch_status_time` (`tenant_id`, `status`, `started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='WhatsApp导入批次审计';

CREATE TABLE `wa_sync_cursor` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '同步水位ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `account_id` bigint NOT NULL COMMENT 'WhatsApp账号ID',
  `source_database` varchar(32) NOT NULL COMMENT '源数据库标识',
  `source_entity` varchar(64) NOT NULL COMMENT '源实体/表名',
  `last_source_pk` bigint DEFAULT NULL COMMENT '最近扫描源主键，仅用于优化',
  `last_scan_at` datetime(3) DEFAULT NULL COMMENT '最近完整扫描时间(UTC)',
  `state_json` json DEFAULT NULL COMMENT '版本化扫描状态',
  `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '删除标记: 0正常 1删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wa_cursor_source` (`tenant_id`, `account_id`, `source_database`, `source_entity`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='WhatsApp扫描水位，仅用于优化';

CREATE TABLE `wa_contact` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'WhatsApp联系人ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `account_id` bigint NOT NULL COMMENT 'WhatsApp账号ID',
  `contact_jid` varchar(191) NOT NULL COMMENT '联系人主JID',
  `lid_jid` varchar(191) DEFAULT NULL COMMENT '联系人LID JID',
  `phone_normalized` varchar(32) DEFAULT NULL COMMENT '标准化号码(E.164 digits-only)',
  `display_name` varchar(191) DEFAULT NULL COMMENT '通讯录显示名',
  `push_name` varchar(191) DEFAULT NULL COMMENT 'WhatsApp push name',
  `business_name` varchar(191) DEFAULT NULL COMMENT 'WhatsApp Business名称',
  `about_text` varchar(500) DEFAULT NULL COMMENT 'WhatsApp About简介',
  `is_business` tinyint NOT NULL DEFAULT 0 COMMENT '是否有商业资料: 0否 1是',
  `profile_file_id` bigint DEFAULT NULL COMMENT '头像文件ID，首版可空',
  `first_seen_at` datetime(3) DEFAULT NULL COMMENT '首次观察时间(UTC)',
  `last_seen_at` datetime(3) DEFAULT NULL COMMENT '最近观察时间(UTC)',
  `raw_metadata` json DEFAULT NULL COMMENT '白名单联系人/商业资料',
  `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '删除标记: 0正常 1删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wa_contact_jid` (`tenant_id`, `account_id`, `contact_jid`),
  KEY `idx_wa_contact_phone` (`tenant_id`, `phone_normalized`, `deleted`),
  KEY `idx_wa_contact_seen` (`tenant_id`, `account_id`, `last_seen_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='WhatsApp联系人';

CREATE TABLE `wa_customer_binding` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'CRM客户绑定ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `wa_contact_id` bigint NOT NULL COMMENT 'WhatsApp联系人ID',
  `customer_id` bigint NOT NULL COMMENT 'CRM客户ID',
  `match_method` varchar(20) NOT NULL COMMENT '匹配方式: EXACT_PHONE/MANUAL',
  `confidence` decimal(5,4) NOT NULL DEFAULT 1.0000 COMMENT '匹配置信度',
  `status` varchar(20) NOT NULL COMMENT '状态: PENDING/CONFIRMED/REJECTED',
  `confirmed_by` bigint DEFAULT NULL COMMENT '确认人ID',
  `confirmed_at` datetime(3) DEFAULT NULL COMMENT '确认时间',
  `note` varchar(500) DEFAULT NULL COMMENT '绑定说明',
  `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '删除标记: 0正常 1删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wa_binding_contact` (`tenant_id`, `wa_contact_id`),
  KEY `idx_wa_binding_customer` (`tenant_id`, `customer_id`, `status`, `deleted`),
  KEY `idx_wa_binding_status` (`tenant_id`, `status`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='WhatsApp联系人与CRM客户绑定';

CREATE TABLE `wa_conversation` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'WhatsApp会话ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `account_id` bigint NOT NULL COMMENT 'WhatsApp账号ID',
  `contact_id` bigint DEFAULT NULL COMMENT 'WhatsApp联系人ID',
  `source_session_pk` bigint DEFAULT NULL COMMENT '本地会话源主键，仅追溯',
  `conversation_jid` varchar(191) NOT NULL COMMENT '会话自然标识JID',
  `conversation_type` varchar(16) NOT NULL COMMENT '会话类型，v1仅DIRECT',
  `title` varchar(255) DEFAULT NULL COMMENT '会话标题',
  `first_message_at` datetime(3) DEFAULT NULL COMMENT '首条消息时间(UTC)',
  `last_message_at` datetime(3) DEFAULT NULL COMMENT '末条消息时间(UTC)',
  `message_count` bigint NOT NULL DEFAULT 0 COMMENT '逻辑消息数',
  `unread_count` int NOT NULL DEFAULT 0 COMMENT '快照时未读数',
  `archived` tinyint NOT NULL DEFAULT 0 COMMENT '是否归档',
  `hidden` tinyint NOT NULL DEFAULT 0 COMMENT '是否隐藏',
  `last_sync_time` datetime(3) DEFAULT NULL COMMENT '最近同步时间(UTC)',
  `raw_metadata` json DEFAULT NULL COMMENT '白名单会话属性',
  `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '删除标记: 0正常 1删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wa_conversation_jid` (`tenant_id`, `account_id`, `conversation_jid`),
  KEY `idx_wa_conversation_contact` (`tenant_id`, `contact_id`, `last_message_at`),
  KEY `idx_wa_conversation_account` (`tenant_id`, `account_id`, `last_message_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='WhatsApp会话';

CREATE TABLE `wa_message` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'WhatsApp逻辑消息ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `account_id` bigint NOT NULL COMMENT 'WhatsApp账号ID',
  `conversation_id` bigint NOT NULL COMMENT 'WhatsApp会话ID',
  `contact_id` bigint DEFAULT NULL COMMENT 'WhatsApp联系人ID',
  `external_message_id` varchar(191) DEFAULT NULL COMMENT 'WhatsApp stanza ID',
  `logical_key_hash` binary(32) NOT NULL COMMENT '版本化逻辑消息SHA-256键',
  `direction` varchar(12) NOT NULL COMMENT '方向: INBOUND/OUTBOUND/SYSTEM',
  `sender_jid` varchar(191) DEFAULT NULL COMMENT '发送方JID',
  `message_type` varchar(32) NOT NULL COMMENT '归一化消息类型',
  `source_message_type` int DEFAULT NULL COMMENT '源消息类型整数',
  `mapping_version` varchar(16) NOT NULL DEFAULT 'v1' COMMENT '类型和逻辑键映射版本',
  `text_content` longtext DEFAULT NULL COMMENT '文本或caption，受权限控制',
  `source_timestamp_ms` bigint NOT NULL COMMENT '源消息时间毫秒值',
  `sent_at` datetime(3) NOT NULL COMMENT '消息时间(UTC)',
  `status` varchar(20) DEFAULT NULL COMMENT '归一化源状态',
  `is_starred` tinyint NOT NULL DEFAULT 0 COMMENT '是否星标',
  `reply_to_external_id` varchar(191) DEFAULT NULL COMMENT '被回复消息外部ID',
  `reply_to_message_id` bigint DEFAULT NULL COMMENT '被回复逻辑消息ID',
  `content_hash` binary(32) DEFAULT NULL COMMENT '规范化内容SHA-256',
  `first_seen_batch_id` bigint NOT NULL COMMENT '首次观察批次ID',
  `last_seen_batch_id` bigint NOT NULL COMMENT '最近观察批次ID',
  `is_revoked` tinyint NOT NULL DEFAULT 0 COMMENT '是否已撤回',
  `revoked_at` datetime(3) DEFAULT NULL COMMENT '撤回观察时间(UTC)',
  `source_deleted` tinyint NOT NULL DEFAULT 0 COMMENT '源端删除事实',
  `raw_metadata` json DEFAULT NULL COMMENT '白名单消息源属性',
  `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT 'ERP隐藏标记: 0正常 1隐藏',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wa_message_logical` (`tenant_id`, `account_id`, `logical_key_hash`),
  KEY `idx_wa_message_conversation` (`tenant_id`, `conversation_id`, `sent_at`, `id`),
  KEY `idx_wa_message_contact` (`tenant_id`, `contact_id`, `sent_at`, `id`),
  KEY `idx_wa_message_external` (`tenant_id`, `account_id`, `external_message_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='WhatsApp逻辑消息';

CREATE TABLE `wa_message_source_ref` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '源行引用ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `account_id` bigint NOT NULL COMMENT 'WhatsApp账号ID',
  `message_id` bigint NOT NULL COMMENT '逻辑消息ID',
  `source_database` varchar(32) NOT NULL COMMENT '源数据库标识',
  `source_entity` varchar(64) NOT NULL COMMENT '源实体/表名',
  `source_pk` bigint NOT NULL COMMENT 'CoreData源主键',
  `source_opt` int DEFAULT NULL COMMENT 'CoreData行版本Z_OPT',
  `source_sort` bigint DEFAULT NULL COMMENT '源排序值',
  `row_hash` binary(32) NOT NULL COMMENT '白名单字段SHA-256',
  `first_seen_batch_id` bigint NOT NULL COMMENT '首次观察批次ID',
  `last_seen_batch_id` bigint NOT NULL COMMENT '最近观察批次ID',
  `source_missing` tinyint NOT NULL DEFAULT 0 COMMENT '完整扫描后源行是否缺失',
  `missing_since_batch_id` bigint DEFAULT NULL COMMENT '首次发现源行缺失的批次ID',
  `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '保留字段，源引用不提供删除动作',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wa_source_ref` (`tenant_id`, `account_id`, `source_database`, `source_entity`, `source_pk`),
  KEY `idx_wa_source_message` (`tenant_id`, `message_id`),
  KEY `idx_wa_source_batch` (`tenant_id`, `account_id`, `last_seen_batch_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='WhatsApp逻辑消息源行映射';

CREATE TABLE `wa_message_media` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '消息媒体ID',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `message_id` bigint NOT NULL COMMENT '逻辑消息ID',
  `media_key_hash` binary(32) NOT NULL COMMENT '消息内媒体稳定SHA-256键',
  `file_id` bigint DEFAULT NULL COMMENT '文件中心file_storage ID',
  `media_type` varchar(20) NOT NULL COMMENT '媒体类型',
  `mime_type` varchar(100) DEFAULT NULL COMMENT '按文件内容识别的MIME类型',
  `original_name` varchar(255) DEFAULT NULL COMMENT '原始文件名，不含绝对路径',
  `file_size` bigint NOT NULL DEFAULT 0 COMMENT '文件大小(byte)',
  `file_hash` binary(32) DEFAULT NULL COMMENT '实际文件SHA-256',
  `caption` text DEFAULT NULL COMMENT '媒体说明',
  `duration_ms` bigint DEFAULT NULL COMMENT '音视频时长(ms)',
  `width` int DEFAULT NULL COMMENT '宽度(px)',
  `height` int DEFAULT NULL COMMENT '高度(px)',
  `source_relative_path` varchar(500) DEFAULT NULL COMMENT '源相对路径，禁止用户名和绝对路径',
  `download_status` varchar(20) NOT NULL DEFAULT 'METADATA_ONLY' COMMENT 'METADATA_ONLY/AVAILABLE/IMPORTED/MISSING/FAILED',
  `error_message` varchar(500) DEFAULT NULL COMMENT '脱敏错误信息',
  `first_seen_batch_id` bigint NOT NULL COMMENT '首次观察批次ID',
  `last_seen_batch_id` bigint NOT NULL COMMENT '最近观察批次ID',
  `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '删除标记: 0正常 1删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wa_media_key` (`tenant_id`, `message_id`, `media_key_hash`),
  KEY `idx_wa_media_file` (`tenant_id`, `file_id`),
  KEY `idx_wa_media_status` (`tenant_id`, `download_status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='WhatsApp消息媒体';
