CREATE TABLE `order_draft` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `external_ref_no` varchar(100) NOT NULL,
  `source_batch_no` varchar(50) DEFAULT NULL,
  `source_order_no` varchar(100) DEFAULT NULL,
  `source_file_id` bigint DEFAULT NULL,
  `raw_customer_name` varchar(255) DEFAULT NULL,
  `raw_customer_phone` varchar(100) DEFAULT NULL,
  `customer_id` bigint DEFAULT NULL,
  `customer_name` varchar(100) NOT NULL DEFAULT '散客',
  `customer_phone` varchar(50) DEFAULT NULL,
  `raw_order_date` varchar(100) DEFAULT NULL,
  `order_date` date DEFAULT NULL,
  `delivery_date` date DEFAULT NULL,
  `raw_deposit` varchar(100) DEFAULT NULL,
  `deposit` decimal(12,2) DEFAULT NULL,
  `paper_total_amount` decimal(12,2) DEFAULT NULL,
  `note` varchar(1000) DEFAULT NULL,
  `warnings` text,
  `status` varchar(20) NOT NULL DEFAULT 'EDITING',
  `confirmed_order_id` bigint DEFAULT NULL,
  `created_by_agent_key_id` bigint DEFAULT NULL,
  `confirmed_by` bigint DEFAULT NULL,
  `confirmed_time` datetime DEFAULT NULL,
  `warning_acknowledged` tinyint NOT NULL DEFAULT 0,
  `deleted` tinyint NOT NULL DEFAULT 0,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_draft_tenant_external_ref` (`tenant_id`, `external_ref_no`),
  KEY `idx_order_draft_tenant_status` (`tenant_id`, `status`, `update_time`),
  KEY `idx_order_draft_confirmed_order` (`confirmed_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='纸质订单识别草稿';

CREATE TABLE `order_draft_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `draft_id` bigint NOT NULL,
  `source_row_no` int DEFAULT NULL,
  `raw_product_code` varchar(255) DEFAULT NULL,
  `raw_description` varchar(1000) DEFAULT NULL,
  `raw_color` varchar(255) DEFAULT NULL,
  `raw_quantity` varchar(100) DEFAULT NULL,
  `raw_sale_price` varchar(100) DEFAULT NULL,
  `raw_amount` varchar(100) DEFAULT NULL,
  `product_id` bigint DEFAULT NULL,
  `sku_id` bigint DEFAULT NULL,
  `quantity` int DEFAULT NULL,
  `sale_price` decimal(12,2) DEFAULT NULL,
  `paper_amount` decimal(12,2) DEFAULT NULL,
  `system_reference_price` decimal(12,2) DEFAULT NULL,
  `match_status` varchar(20) NOT NULL DEFAULT 'UNMATCHED',
  `match_candidates` text,
  `warnings` text,
  `deleted` tinyint NOT NULL DEFAULT 0,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_order_draft_item_draft` (`tenant_id`, `draft_id`, `deleted`),
  KEY `idx_order_draft_item_sku` (`sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='纸质订单识别草稿明细';
